_8.WebApp/Models/ErrorViewModel.cs
namespace _8.WebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

_8.WebApp/Models/LoginModel.cs
namespace _8.WebApp.Models;

#pragma warning disable
public class LoginModel
{
    public string Username { get; set; }
    public string Password { get; set; }
}

_8.WebApp/Models/Role.cs
namespace _8.WebApp.Models;

#pragma warning disable
public class Role
{
    public string Name { get; set; }
    public List<string> Permissions { get; set; }
}

_8.WebApp/Models/UserData.cs
namespace _8.WebApp.Models;

#pragma warning disable
public class UserData
{
    public string UserId { get; set; }
    public string? Avatar { get; set; }
    public string? Email { get; set; }
    public string? DisplayName { get; set; }
    public string UserName { get; set; }
    public string Role { get; set; }
    public List<string> Permissions { get; set; }
}

_8.WebApp/Controllers/AuthController.cs
using _0.Share.IServices;
using _0.Share.ViewModels;
using _8.WebApp.Services.IServices;
using Microsoft.AspNetCore.Mvc;

namespace _8.WebApp.Controllers;

public class AuthController : Controller
{
    private readonly IAuthService _authService;
    private readonly ICookieAuthService _cookieAuthService;
    private readonly ICookieTokenService _cookieTokenService;
    private readonly ICookieUserDataService _cookieUserDataService;

    public AuthController(
        IAuthService authService,
        ICookieAuthService cookieAuthService,
        ICookieTokenService cookieTokenService,
        ICookieUserDataService cookieUserDataService)
    {
        _authService = authService;
        _cookieAuthService = cookieAuthService;
        _cookieTokenService = cookieTokenService;
        _cookieUserDataService = cookieUserDataService;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Login(LoginRequest dto, string? returnUrl)
    {
        if (ModelState.IsValid)
        {
            var response = await _authService.LoginAsync(dto);
            if (response != null)
            {
                await _cookieAuthService.SignInAsync(response);
                TempData["success"] = "Login successfully.";
                if (returnUrl != null && returnUrl.Length > 0)
                    return Redirect(returnUrl);
                return RedirectToAction("Index", "Home");
            }
        }
        TempData["error"] = "Login failed, please check your credentials.";
        return View(dto);
    }

    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Register(RegisterRequest model)
    {
        if (ModelState.IsValid)
        {
            var response = await _authService.RegisterAsync(model);
            if (response != null)
            {
                TempData["success"] = "Register successfully.";
                return RedirectToAction(nameof(Login));
            }
        }
        TempData["error"] = "Encountered error.";
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Logout()
    {
        await _cookieAuthService.SignOutAsync();
        return RedirectToAction("Index", "Home");
    }

    [HttpGet]
    public IActionResult AccessDenied()
    {
        return View();
    }
}

_8.WebApp/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;

namespace _8.WebApp.Controllers;

public class ErrorController : Controller
{
    public ErrorController()
    {
    }

    [Route("404")]
    [HttpGet]
    public IActionResult PageNotFound()
    {
        string originalPath = "unknown";
        if (HttpContext.Items.ContainsKey("originalPath"))
        {
            originalPath = HttpContext.Items["originalPath"] as string ?? "";
        }
        return View();
    }
}

_8.WebApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _0.Share.IServices;
using _8.WebApp.Models;

namespace _8.WebApp.Controllers;

public class HomeController : Controller
{
    private readonly IUserService _userService;

    public HomeController(IUserService userService)
    {
        _userService = userService;
    }

    public async Task<IActionResult> Index()
    {
        var items = await _userService.GetAll();
        return View(items);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

_8.WebApp/Controllers/UserController.cs
using _0.Share.IServices;
using _0.Share.ViewModels.User;
using Microsoft.AspNetCore.Mvc;

namespace _8.WebApp.Controllers;

public class UserController : Controller
{
    private readonly IUserService _userService;

    public UserController(IUserService userService)
    {
        _userService = userService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var items = await _userService.GetAll();
        return View(items);
    }

    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        var item = await _userService.GetOne(id);
        if (item != null)
            return View(item);
        return NotFound();
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(UserCreateDto model)
    {
        if (ModelState.IsValid)
        {
            var item = await _userService.Create(model);
            if (item != null)
            {
                TempData["success"] = "Created successfully.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("ErrorMessages", "Create failed.");
            }
        }
        TempData["error"] = "Encountered error.";
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var item = await _userService.GetOne(id);
        if (item != null)
        {
            TempData["id"] = id;
            return View(item);
        }
        return NotFound();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, UserUpdateDto model)
    {
        if (ModelState.IsValid)
        {
            var item = await _userService.Update(id, model);
            if (item != null)
            {
                TempData["success"] = "Updated successfully.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("ErrorMessages", "Update failed.");
            }
        }
        TempData["error"] = "Encountered error.";
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        var item = await _userService.GetOne(id);
        if (item != null)
            return View(item);
        return NotFound();
    }

    [HttpPost]
    public async Task<IActionResult> Delete(UserDto model)
    {
        var item = await _userService.Delete(model.Id);
        if (item != null)
        {
            TempData["success"] = "Deleted successfully.";
            return RedirectToAction(nameof(Index));
        }
        else
        {
            ModelState.AddModelError("ErrorMessages", "Delete failed.");
        }
        TempData["error"] = "Encountered error.";
        return View(model);
    }
}

_8.WebApp/Views/Home/Index.cshtml
@using _0.Share.ViewModels.User
@using Microsoft.AspNetCore.Components
@model IEnumerable<UserDto>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


<img class="d-block w-100" src="images/home/slide1.jpg" alt="">

<hr />
<div class="row" style="--bs-gutter-x:0">
    @foreach (var item in Model)
    {
        <div class="p-4 col-md-12 col-lg-6">
            <div class="row" style="border-radius:20px; border: 1px solid #ffffff">
                <div class="col-4">
                    <img class="d-block w-100" style="border-radius:20px;" src="" alt="@item.Id">
                </div>
                <div class="col-8">
                    <p class="card-title text-warning" style="font-size:xx-large">@item.DisplayName</p>
                    <p class="card-text">
                        @((MarkupString)item.CreatedAt.ToString("dd/MM/yyyy"))
                    </p>
                </div>
                <div class="col-12">
                    <div class="row pb-3 pt-2">
                        <div class="col-4">
                            <a href="" class="btn btn-success form-control btn-block">View</a>
                        </div>
                        <div class="col-4">
                            <span class="">Id : @item.Id</span><br />
                            <span class=" pt-1">Role : @item.Role</span><br />
                        </div>
                        <div class="col-4">
                            <span class="text-warning float-end font-weight-bold pt-1" style="font-size:25px;">
                                USD
                                <span style="border-bottom:1px solid #ff6a00">
                                    @item.Money.ToString("c")
                                </span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

_8.WebApp/Views/Shared/_Layout.cshtml
@using _8.WebApp.Services.IServices
@inject ICookieAuthService cookieAuthService
@inject ICookieUserDataService cookieUserDataService

@if(TempData["success"] != null)
{
    <div class="alert alert-success auto-hide">@TempData["success"]</div>
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _8.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_8.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_8.WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Index">Auth</a>
                        </li>

                        @if(cookieAuthService.IsAuthenticated())
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                    
                    <!-- avatar -->
                    <div class="dropdown d-inline-block ms-2">
                        <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @if(cookieUserDataService.GetUserData()?.Avatar != null)
                            {
                                <img class="rounded-circle header-profile-user" src="@cookieUserDataService.GetUserData()?.Avatar"
                                                            alt="Header Avatar">
                            }else{
                                <img class="rounded-circle header-profile-user" src="~/assets/images/users/avatar-1.jpg"
                                                            alt="Header Avatar">
                            }
                        </button>
                        
                        <div class="dropdown-menu dropdown-menu-end">
                            <!-- item-->
                            <a class="dropdown-item" href="#">
                                <i class="dripicons-user font-size-16 align-middle me-2"></i>
                                Profile
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="dripicons-wallet font-size-16 align-middle me-2"></i> My
                                Wallet
                            </a>
                            <a class="dropdown-item d-block" href="#">
                                <span class="badge bg-success float-end">5</span><i
                                    class="dripicons-gear font-size-16 align-middle me-2"></i> Settings
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="dripicons-lock font-size-16 align-middle me-2"></i> Lock
                                screen
                            </a>
                            <div class="dropdown-divider"></div>
                            @if(cookieAuthService.IsAuthenticated()){
                                <a class="dropdown-item" href="/Auth/logout">
                                    <i class="dripicons-exit font-size-16 align-middle me-2"></i>
                                    Logout
                                </a>
                            }else{
                                <a class="dropdown-item text-danger" href="/Auth/login">
                                    <i class="dripicons-exit font-size-16 align-middle me-2 text-danger"></i>
                                    Login
                                </a>
                            }
                        </div>
                    </div>


                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - _8.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script>
    $(document).ready(function() {
        setTimeout(function() {
            $(".auto-hide").fadeOut("slow", function() {
                $(this).remove();
            });
        }, 3000); // 3 seconds
    });
</script>

_8.WebApp/Views/Shared/_LayoutUser.cshtml
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Login | DoVT2 - Responsive Bootstrap 5 Admin Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="~/assets/images/favicon.ico">

    <!-- Bootstrap Css -->
    <link href="~/assets/css/bootstrap.min.css" id="bootstrap-style" rel="stylesheet" type="text/css" />

    <!-- Icons Css -->
    <link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="~/assets/css/app.min.css" id="app-style" rel="stylesheet" type="text/css" />


</head>

<body class="account-bg">

    <!-- Loader -->
    <div id="preloader">
        <div id="status">
            <div class="spinner"></div>
        </div>
    </div>

    <div class="account-pages my-5 pt-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center mt-4">
                                <div class="mb-3">
                                    <a href="index.html" class="auth-logo">
                                        <img src="~/assets/images/logo-dark.png" height="30" class="logo-dark mx-auto"
                                            alt="">
                                        <img src="~/assets/images/logo-light.png" height="30" class="logo-light mx-auto"
                                            alt="">
                                    </a>
                                </div>
                            </div>
                            @RenderBody()

                        </div>
                    </div>
                    <div class="mt-5 text-center">
                        <p>Don't have an account ? <a href="pages-register.html" class="fw-bold text-primary"> Signup
                                Now </a> </p>
                        <p>©
                            <script>document.write(new Date().getFullYear())</script> With <i
                                class="mdi mdi-heart text-danger"></i> by DoVT2
                        </p>
                    </div>

                </div>
            </div>
        </div>
    </div>


    <!-- JAVASCRIPT -->
    <script src="~/assets/libs/jquery/jquery.min.js"></script>
    <script src="~/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/libs/metismenu/metisMenu.min.js"></script>
    <script src="~/assets/libs/simplebar/simplebar.min.js"></script>
    <script src="~/assets/libs/node-waves/waves.min.js"></script>

    <script src="~/assets/js/app.js"></script>

</body>

</html>

_8.WebApp/Views/Shared/_LeftSidebar.cshtml
<!-- Left sidebar -->
<div class="email-leftbar card">
        <a asp-controller = "Email" asp-action="Compose" class="btn btn-danger rounded-pill btn-custom btn-block waves-effect waves-light">Compose</a>


    <div class="mail-list mt-4">
        <a href="#" class="active">All<span class="ms-1">(18)</span><span
                class="mdi mdi-arrow-right-drop-circle text-purple float-end mt-1"></span></a>
        <a href="#">Draft<span class="mdi mdi-arrow-right-drop-circle text-success float-end mt-1"></span></a>
        <a href="#">Scheduled<span class="mdi mdi-arrow-right-drop-circle text-warning float-end mt-1"></span></a>
        <a href="#">Sent Mail<span class="mdi mdi-arrow-right-drop-circle text-pink float-end mt-1"></span></a>
    </div>

    <h6 class="mt-4">Chat</h6>

    <div class="mt-4">
        <a href="#" class="d-flex">
            <img class="d-flex me-3 rounded-circle" src="~/assets/images/users/avatar-2.jpg"
                alt="Generic placeholder image" height="36">
            <div class="flex-1 chat-user-box">
                <p class="user-title m-0">Scott Median</p>
                <p class="text-muted text-truncate">Hello</p>
            </div>
        </a>

        <a href="#" class="d-flex">
            <img class="d-flex me-3 rounded-circle" src="~/assets/images/users/avatar-3.jpg"
                alt="Generic placeholder image" height="36">
            <div class="flex-1 chat-user-box">
                <p class="user-title m-0">Julian Rosa</p>
                <p class="text-muted text-truncate">What about our next..</p>
            </div>
        </a>

        <a href="#" class="d-flex">
            <img class="d-flex me-3 rounded-circle" src="~/assets/images/users/avatar-4.jpg"
                alt="Generic placeholder image" height="36">
            <div class="flex-1 chat-user-box">
                <p class="user-title m-0">David Medina</p>
                <p class="text-muted text-truncate">Yeah everything is fine</p>
            </div>
        </a>

        <a href="#" class="d-flex">
            <img class="d-flex me-3 rounded-circle" src="~/assets/images/users/avatar-6.jpg"
                alt="Generic placeholder image" height="36">
            <div class="flex-1 chat-user-box">
                <p class="user-title m-0">Jay Baker</p>
                <p class="text-muted text-truncate">Wow's great</p>
            </div>
        </a>
    </div>
</div>
<!-- End Left sidebar -->

_8.WebApp/Views/User/Create.cshtml
@model _0.Share.ViewModels.User.UserCreateDto

<form asp-action="Create">
    <br />
    <h1 class="text-primary">Create User</h1>

    <div class="row">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="col-2">
            <label asp-for="FirstName" class="control-label pt-2" style="font-size:20px"></label>
        </div>
        <div class="col-10">
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>

        <div class="col-2">
            <label asp-for="LastName" class="control-label pt-2" style="font-size:20px"></label>
        </div>
        <div class="col-10">
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>

        <div class="col-2">
            <label asp-for="Username" class="control-label pt-2" style="font-size:20px"></label>
        </div>
        <div class="col-10">
            <input asp-for="Username" class="form-control" />
            <span asp-validation-for="Username" class="text-danger"></span>
        </div>

        <div class="col-2">
            <label asp-for="HashPassword" class="control-label pt-2" style="font-size:20px"></label>
        </div>
        <div class="col-10 pb-3">
            <input asp-for="HashPassword" class="form-control" />
            <span asp-validation-for="HashPassword" class="text-danger"></span>
        </div>

        <div class="col-2">
            <label asp-for="Role" class="control-label pt-2" style="font-size:20px"></label>
        </div>
        <div class="col-10 pb-3">
            <input asp-for="Role" class="form-control" />
            <span asp-validation-for="Role" class="text-danger"></span>
        </div>

        <div class="col-2">
            <label asp-for="ManagerId" class="control-label pt-2" style="font-size:20px"></label>
        </div>
        <div class="col-10 pb-3">
            <input asp-for="ManagerId" class="form-control" />
            <span asp-validation-for="ManagerId" class="text-danger"></span>
        </div>

        <div class="col-5 offset-2">
            <a asp-action="Create" asp-controller="User" class="btn-primary btn form-control">Back to list</a>
        </div>
        <div class="col-5">
            <input type="submit" value="Create" class="btn btn-success form-control" />
        </div>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

_8.WebApp/Views/User/Delete.cshtml
@model _0.Share.ViewModels.User.UserDto

@{
    ViewData["Title"] = "Delete";
}

<h1>DeleteVilla</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VillaDTO</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DisplayName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DisplayName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Money)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Money)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input hidden asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

_8.WebApp/Views/User/Details.cshtml
@model _0.Share.ViewModels.User.UserDto

@{
    ViewData["Title"] = "Details";
}

<h1>DetailUser</h1>

<div>
    <h4>UserDto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Money)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Money.ToString("c"))
        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DisplayName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DisplayName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt.ToString("dd/MM/yyyy"))
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt.ToString("dd/MM/yyyy"))
        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Id  }) |
    <a asp-action="Index">Back to List</a>
</div>

_8.WebApp/Views/User/Edit.cshtml
@model _0.Share.ViewModels.User.UserUpdateDto

@{
    ViewData["Title"] = "Edit";
}

<h1>UpdateUser</h1>

<h4>UserUpdateDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input hidden asp-for="Id" />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

_8.WebApp/Views/User/Index.cshtml
@model IEnumerable<_0.Share.ViewModels.User.UserDto>
<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class=" = col">
            <h1 class="text-primary">User List</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-controller="User" asp-action="Create" a class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create new User</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Display Name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Money
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.DisplayName</td>
                    <td>@item.Email</td>
                    <td>@((item.Money).ToString("c"))</td>
                    <td>
                        <a asp-controller="User" asp-action="Details" asp-route-id="@item.Id" a class="btn btn-success"><i class="bi bi-pencil-fill"></i>Details</a>
                        <a asp-controller="User" asp-action="Edit" asp-route-id="@item.Id" a class="btn btn-success"><i class="bi bi-pencil-fill"></i>Edit</a>
                        <a asp-controller="User" asp-action="Delete" asp-route-id="@item.Id" a class="btn btn-danger"><i class="bi bi-trash-fill"></i>Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>